[package]
name = "clamps"
version = "0.1.0"
authors = ["Laura Powles <laura@laurapowles.com>"]
edition = "2021"

license-file = "LICENSE"
description = "Wrapping, saturating, and other forms of number clamping"
repository = "https://github.com/nebulaeandstars/clamps"

[dependencies]
