hard_tabs = false
max_width = 80
blank_lines_upper_bound = 2

wrap_comments = true
comment_width = 80

imports_granularity = "Module"
group_imports = "StdExternalCrate"

fn_args_layout = "Compressed"

use_field_init_shorthand = true
use_small_heuristics = "Max"

enum_discrim_align_threshold = 20
struct_field_align_threshold = 20

empty_item_single_line = true
fn_single_line = true

indent_style = "Block"
format_strings = true
overflow_delimited_expr = true

format_code_in_doc_comments = true

match_block_trailing_comma = true
trailing_semicolon = true

match_arm_leading_pipes = "Preserve" # unsure about this one
match_arm_blocks = false
